# Basic
title: Zijian Zhao (赵子健, Aric)
subtitle: Aric.Zhao@outlook.com
description: I am a Research Engineer in the field of Computer Vision and Machine Learning working at Institute of Computing Technology, Chinese Academy of Science. 
# 头像里面的标题
avatarTitle: AI
# 头像里面的描述
avatarDesc: Computer Vision
url: "http://www.zijian-zhao.com"

# Comment
comment:
    disqus: leopard
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    #github: JasonZhao001
    #zhihu: JasonZhao666
    mail: aric.zhao@outlook.com
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 


# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: xxxx  
#    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    - {title: 关于我, description: about, url: '/about'} 

# Navigation buttons in the front page.s
nav:
    #- {title: Experience, description: , url: '/archive'}   
    #- {title: Projects, description: projects, url: '/tags'}  
    #- {title: Papers, description: papers, url: '/tags'}    
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


