# Basic
title: 赵子健
subtitle: Zijian Zhao
description: 智能让世界更美好
# 头像里面的标题
avatarTitle: Jason
# 头像里面的描述
avatarDesc: Computer Vision
url: "http://www.zijian-zhao.com"

# Comment
comment:
    disqus: leopard
    # gitment: xxx // 需要修改 comments.html中的client_id和client_secret
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726 
    #github: JasonZhao001
    zhihu: JasonZhao666
    mail: zhaozijianzzj@gmail.com
    # juejin: xxx
    # jianshu: 2ada30d8d0f7
    # twitter: 


# 百度统计 
# 使用博客模板请去掉或者更换 id 
#baidu:
#    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: xxxx  
#    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签归类, description: tags, url: '/tags'}    
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


